const DEFAULT_METADATA = {
    sourceRefs: [],
    lastReviewed: null,
    regionScope: 'US-general',
    evidence: {
        spacing: 'low',
        neighbors: 'low',
        window: 'low',
    },
};

const RAW_PLANT_DATABASE = [
    {
        id: 'tomato',
        name: 'Tomato',
        category: 'vegetables',
        icon: '🍅',
        color: 'bg-red-500',
        spacingInches: 24,
        goodNeighbors: ['basil', 'carrot', 'onion', 'marigold', 'parsley'],
        avoidNeighbors: ['potato', 'corn'],
        plantingWindow: { start: 3, end: 5 },
        notes: 'Needs support and airflow; prune lower leaves.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Tomatoes',
                url: 'https://extension.umn.edu/vegetables/growing-tomatoes',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'carrot',
        name: 'Carrot',
        category: 'vegetables',
        icon: '🥕',
        color: 'bg-orange-500',
        spacingInches: 3,
        goodNeighbors: ['onion', 'lettuce', 'radish', 'tomato'],
        avoidNeighbors: [],
        plantingWindow: { start: 2, end: 8 },
        notes: 'Keep soil loose and stone-free.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Carrots',
                url: 'https://extension.umn.edu/vegetables/growing-carrots',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'lettuce',
        name: 'Lettuce',
        category: 'vegetables',
        icon: '🥬',
        color: 'bg-green-400',
        spacingInches: 10,
        goodNeighbors: ['carrot', 'onion', 'radish', 'strawberry'],
        avoidNeighbors: ['parsley'],
        plantingWindow: { start: 2, end: 5 },
        notes: 'Prefers cooler weather and even moisture.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'medium', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Lettuce in Home Gardens',
                url: 'https://extension.umn.edu/vegetables/growing-lettuce',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'pepper',
        name: 'Pepper',
        category: 'vegetables',
        icon: '🫑',
        color: 'bg-green-600',
        spacingInches: 18,
        goodNeighbors: ['basil', 'onion', 'carrot', 'marigold'],
        avoidNeighbors: ['bean'],
        plantingWindow: { start: 3, end: 5 },
        notes: 'Warm-season crop; avoid cold snaps.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Peppers in the Home Garden',
                url: 'https://yardandgarden.extension.iastate.edu/how-to/growing-peppers-home-garden',
                publisher: 'Iowa State University Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'onion',
        name: 'Onion',
        category: 'vegetables',
        icon: '🧅',
        color: 'bg-yellow-600',
        spacingInches: 4,
        goodNeighbors: ['carrot', 'lettuce', 'tomato', 'pepper'],
        avoidNeighbors: ['bean'],
        plantingWindow: { start: 1, end: 4 },
        notes: 'Consistent watering prevents splitting.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Onions in Home Gardens',
                url: 'https://extension.umn.edu/vegetables/growing-onions-home-gardens',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'broccoli',
        name: 'Broccoli',
        category: 'vegetables',
        icon: '🥦',
        color: 'bg-green-700',
        spacingInches: 18,
        goodNeighbors: ['onion', 'beet'],
        avoidNeighbors: ['tomato', 'strawberry'],
        plantingWindow: { start: 2, end: 4 },
        notes: 'Feed well and keep evenly moist.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Broccoli in Home Gardens',
                url: 'https://extension.umn.edu/vegetables/growing-broccoli',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Alternaria leaf spot and head rot of Brassica crops',
                url: 'https://extension.umn.edu/disease-management/alternaria-leaf-blight',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'potato',
        name: 'Potato',
        category: 'vegetables',
        icon: '🥔',
        color: 'bg-yellow-700',
        spacingInches: 14,
        goodNeighbors: ['bean', 'corn'],
        avoidNeighbors: ['tomato'],
        plantingWindow: { start: 2, end: 4 },
        notes: 'Hill soil around stems as plants grow.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Potatoes in Home Gardens',
                url: 'https://extension.umn.edu/vegetables/growing-potatoes',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'bean',
        name: 'Bean',
        category: 'vegetables',
        icon: '🫘',
        color: 'bg-emerald-600',
        spacingInches: 6,
        goodNeighbors: ['corn', 'radish', 'potato'],
        avoidNeighbors: ['onion', 'garlic', 'pepper'],
        plantingWindow: { start: 4, end: 6 },
        notes: 'Do not over-fertilize with nitrogen.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Beans in Home Gardens',
                url: 'https://extension.umn.edu/vegetables/growing-beans',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'radish',
        name: 'Radish',
        category: 'vegetables',
        icon: '🔴',
        color: 'bg-pink-500',
        spacingInches: 3,
        goodNeighbors: ['carrot', 'lettuce', 'bean', 'spinach'],
        avoidNeighbors: [],
        plantingWindow: { start: 2, end: 8 },
        notes: 'Fast crop; succession sow every 1-2 weeks.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Radishes in Home Gardens',
                url: 'https://extension.umn.edu/vegetables/growing-radishes',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'spinach',
        name: 'Spinach',
        category: 'vegetables',
        icon: '🍃',
        color: 'bg-green-800',
        spacingInches: 5,
        goodNeighbors: ['strawberry', 'radish'],
        avoidNeighbors: ['potato'],
        plantingWindow: { start: 1, end: 4 },
        notes: 'Bolts quickly in heat; choose spring/fall windows.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Spinach and Swiss Chard in Home Gardens',
                url: 'https://extension.umn.edu/vegetables/growing-spinach-and-swiss-chard',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'zucchini',
        name: 'Zucchini',
        category: 'vegetables',
        icon: '🥒',
        color: 'bg-green-500',
        spacingInches: 30,
        goodNeighbors: ['corn', 'bean', 'marigold'],
        avoidNeighbors: ['potato'],
        plantingWindow: { start: 4, end: 6 },
        notes: 'Needs room and frequent harvest to stay productive.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Summer Squash and Zucchini in Home Gardens',
                url: 'https://extension.umn.edu/vegetables/growing-summer-squash-and-zucchini',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'corn',
        name: 'Corn',
        category: 'vegetables',
        icon: '🌽',
        color: 'bg-yellow-400',
        spacingInches: 12,
        goodNeighbors: ['bean', 'zucchini', 'potato'],
        avoidNeighbors: ['tomato'],
        plantingWindow: { start: 3, end: 5 },
        notes: 'Plant in blocks for pollination.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Sweet Corn in Home Gardens',
                url: 'https://extension.umn.edu/vegetables/growing-sweet-corn',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'eggplant',
        name: 'Eggplant',
        category: 'vegetables',
        icon: '🍆',
        color: 'bg-purple-700',
        spacingInches: 18,
        goodNeighbors: ['bean', 'pepper', 'marigold'],
        avoidNeighbors: [],
        plantingWindow: { start: 4, end: 6 },
        notes: 'Warm-season crop with heavy feeding needs.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Eggplant in Home Gardens',
                url: 'https://extension.umn.edu/vegetables/growing-eggplant',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'beet',
        name: 'Beet',
        category: 'vegetables',
        icon: '🍠',
        color: 'bg-rose-800',
        spacingInches: 4,
        goodNeighbors: ['onion', 'lettuce', 'broccoli'],
        avoidNeighbors: ['bean'],
        plantingWindow: { start: 2, end: 6 },
        notes: 'Thin seedlings early for best root size.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'medium', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Beets in Home Gardens',
                url: 'https://extension.umn.edu/vegetables/beets',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'garlic',
        name: 'Garlic',
        category: 'vegetables',
        icon: '🧄',
        color: 'bg-stone-200',
        spacingInches: 6,
        goodNeighbors: ['tomato', 'carrot', 'strawberry'],
        avoidNeighbors: ['bean'],
        plantingWindow: { start: 9, end: 10 },
        notes: 'Often planted in fall for next summer harvest.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'medium', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Garlic in the Home Garden',
                url: 'https://extension.umn.edu/vegetables/growing-garlic',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'basil',
        name: 'Basil',
        category: 'herbs',
        icon: '🌿',
        color: 'bg-green-500',
        spacingInches: 12,
        goodNeighbors: ['tomato', 'pepper'],
        avoidNeighbors: [],
        plantingWindow: { start: 4, end: 6 },
        notes: 'Pinch tips often to delay flowering.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'medium', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Basil',
                url: 'https://extension.umn.edu/vegetables/growing-basil',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'parsley',
        name: 'Parsley',
        category: 'herbs',
        icon: '🌿',
        color: 'bg-green-600',
        spacingInches: 8,
        goodNeighbors: ['tomato'],
        avoidNeighbors: ['lettuce'],
        plantingWindow: { start: 3, end: 6 },
        notes: 'Slow germination; keep seed bed moist.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'medium', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Parsley',
                url: 'https://extension.umn.edu/vegetables/growing-parsley',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'mint',
        name: 'Mint',
        category: 'herbs',
        icon: '🍃',
        color: 'bg-emerald-400',
        spacingInches: 18,
        goodNeighbors: ['tomato'],
        avoidNeighbors: [],
        plantingWindow: { start: 3, end: 6 },
        notes: 'Aggressive spreader; consider container use.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'medium', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Mint',
                url: 'https://extension.umn.edu/vegetables/growing-mint',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'rosemary',
        name: 'Rosemary',
        category: 'herbs',
        icon: '🌲',
        color: 'bg-green-800',
        spacingInches: 24,
        goodNeighbors: ['bean'],
        avoidNeighbors: ['basil'],
        plantingWindow: { start: 3, end: 5 },
        notes: 'Needs good drainage and lots of sun.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'medium', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Rosemary',
                url: 'https://plants.ces.ncsu.edu/plants/salvia-rosemarinus/',
                publisher: 'NC State Extension Plant Toolbox',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'thyme',
        name: 'Thyme',
        category: 'herbs',
        icon: '🌿',
        color: 'bg-stone-500',
        spacingInches: 10,
        goodNeighbors: ['strawberry'],
        avoidNeighbors: [],
        plantingWindow: { start: 3, end: 6 },
        notes: 'Low grower; great border herb.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'medium', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Thymus vulgaris',
                url: 'https://plants.ces.ncsu.edu/plants/thymus-vulgaris/',
                publisher: 'NC State Extension Plant Toolbox',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'lavender',
        name: 'Lavender',
        category: 'herbs',
        icon: '🪻',
        color: 'bg-purple-400',
        spacingInches: 24,
        goodNeighbors: ['daisy'],
        avoidNeighbors: ['mint'],
        plantingWindow: { start: 3, end: 5 },
        notes: 'Needs dry feet and full sun.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'medium', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Lavandula angustifolia',
                url: 'https://plants.ces.ncsu.edu/plants/lavandula-angustifolia/',
                publisher: 'NC State Extension Plant Toolbox',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'sunflower',
        name: 'Sunflower',
        category: 'flowers',
        icon: '🌻',
        color: 'bg-yellow-500',
        spacingInches: 12,
        goodNeighbors: ['corn'],
        avoidNeighbors: ['potato'],
        plantingWindow: { start: 3, end: 6 },
        notes: 'Tall plants can shade nearby beds.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'medium', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Helianthus annuus',
                url: 'https://plants.ces.ncsu.edu/plants/helianthus-annuus/',
                publisher: 'NC State Extension Plant Toolbox',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'marigold',
        name: 'Marigold',
        category: 'flowers',
        icon: '🌼',
        color: 'bg-orange-400',
        spacingInches: 10,
        goodNeighbors: ['tomato', 'pepper', 'zucchini'],
        avoidNeighbors: ['bean'],
        plantingWindow: { start: 3, end: 6 },
        notes: 'Useful companion for many vegetables.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'medium', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Tagetes spp. (Marigold)',
                url: 'https://plants.ces.ncsu.edu/plants/tagetes-spp/',
                publisher: 'NC State Extension Plant Toolbox',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'daisy',
        name: 'Daisy',
        category: 'flowers',
        icon: '🌼',
        color: 'bg-white',
        spacingInches: 12,
        goodNeighbors: ['lavender'],
        avoidNeighbors: [],
        plantingWindow: { start: 3, end: 6 },
        notes: 'Moderate water and regular deadheading.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'medium', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Leucanthemum x superbum',
                url: 'https://plants.ces.ncsu.edu/plants/leucanthemum-x-superbum/',
                publisher: 'NC State Extension Plant Toolbox',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'tulip',
        name: 'Tulip',
        category: 'flowers',
        icon: '🌷',
        color: 'bg-pink-400',
        spacingInches: 5,
        goodNeighbors: ['daisy'],
        avoidNeighbors: [],
        plantingWindow: { start: 8, end: 10 },
        notes: 'Plant bulbs in fall for spring bloom.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'medium', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Tulipa gesneriana',
                url: 'https://plants.ces.ncsu.edu/plants/tulipa-gesneriana/',
                publisher: 'NC State Extension Plant Toolbox',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'strawberry',
        name: 'Strawberry',
        category: 'fruits',
        icon: '🍓',
        color: 'bg-red-600',
        spacingInches: 12,
        goodNeighbors: ['lettuce', 'spinach', 'garlic', 'thyme'],
        avoidNeighbors: ['broccoli'],
        plantingWindow: { start: 2, end: 4 },
        notes: 'Mulch well and remove runners for bigger berries.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Strawberries in the Home Garden',
                url: 'https://extension.umn.edu/fruit/growing-strawberries-home-garden',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'blueberry',
        name: 'Blueberry',
        category: 'fruits',
        icon: '🫐',
        color: 'bg-blue-600',
        spacingInches: 48,
        goodNeighbors: ['thyme', 'strawberry'],
        avoidNeighbors: [],
        plantingWindow: { start: 2, end: 4 },
        notes: 'Requires acidic soil and steady moisture.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Growing Blueberries in the Home Garden',
                url: 'https://extension.umn.edu/fruit/growing-blueberries-home-garden',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
    {
        id: 'raspberry',
        name: 'Raspberry',
        category: 'fruits',
        icon: '🍇',
        color: 'bg-rose-500',
        spacingInches: 36,
        goodNeighbors: ['marigold', 'garlic'],
        avoidNeighbors: ['potato', 'tomato'],
        plantingWindow: { start: 2, end: 4 },
        notes: 'Prune annually for healthy canes.',
        lastReviewed: '2026-02-22',
        regionScope: 'US-home-garden (extension-derived)',
        evidence: { spacing: 'high', neighbors: 'low', window: 'low' },
        sourceRefs: [
            {
                title: 'Raspberries for the Home Garden',
                url: 'https://extension.umn.edu/fruit/raspberries-home-garden',
                publisher: 'University of Minnesota Extension',
                lastChecked: '2026-02-22',
            },
            {
                title: 'Companion Planting (evidence caveats)',
                url: 'https://agrilifeextension.tamu.edu/library/gardening/companion-planting/',
                publisher: 'Texas A&M AgriLife Extension',
                lastChecked: '2026-02-22',
            },
        ],
    },
];

export const PLANT_DATABASE = RAW_PLANT_DATABASE.map((plant) => ({
    ...DEFAULT_METADATA,
    ...plant,
    evidence: {
        ...DEFAULT_METADATA.evidence,
        ...(plant.evidence || {}),
    },
    sourceRefs: Array.isArray(plant.sourceRefs) ? plant.sourceRefs : [],
}));
